name: savour_deals_flutter
description: Savour Deals
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+11

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  fluttertoast: ^7.0.0
  auto_size_text: ^2.1.0
  flutter_platform_widgets: ^0.60.2
  timeago: ^2.0.27
  flutter_advanced_networkimage: #^0.8.0
    git:
      url: https://github.com/mchome/flutter_advanced_networkimage.git

  firebase_auth: ^0.18.0

  latlong: ^0.6.1
  geolocator: ^6.0.0
  location_permissions: ^3.0.0
  google_maps_flutter: ^0.5.31
  in_app_purchase: ^0.3.4

  firebase_database: ^4.0.0
  flutter_geofire:
    git:
      url: https://github.com/Savour-Deals/flutter_geofire.git
    # path: "../flutter_geofire"
  rxdart: ^0.24.0

  app_settings: ^4.0.3
  onesignal_flutter: ^2.0.0
  firebase_analytics: ^6.0.0
  firebase_crashlytics: ^0.1.3+3
  firebase_core: ^0.5.0
  firebase_messaging: ^7.0.0
  # flutter_local_notifications: ^0.8.2

  google_api_availability: ^2.0.3

  showcaseview: ^0.1.6
  rate_my_app: ^0.7.0
  shared_preferences: ^0.5.10
  url_launcher: ^5.5.0
  barcode_scan: ^3.0.0
  share: ^0.6.5
  provider: ^4.0.0

  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  meta: ^1.2.0
  equatable: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: SavourIcons
      fonts:
        - asset: fonts/SavourIcons.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  # - family: SavourIcons
  #   fonts:
  #     - asset: fonts/SavourIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttfs
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
