name: savour_deals_flutter
description: Savour Deals
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+11

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  fluttertoast: ^3.1.3
  auto_size_text: ^2.1.0
  flutter_platform_widgets: ^0.32.4
  timeago: ^2.0.26
  flutter_advanced_networkimage: ^0.7.0
    # git:
    #   url: https://github.com/mchome/flutter_advanced_networkimage.git

  firebase_auth: 0.15.4
  flutter_facebook_login: ^3.0.0
  flutter_auth_buttons: ^0.7.0

  latlong: ^0.6.1
  geolocator: ^5.3.0
  location_permissions: ^2.0.5
  google_maps_flutter: ^0.5.24+1

  firebase_database: ^3.1.3
  flutter_geofire:
    git:
      url: https://github.com/Savour-Deals/flutter_geofire.git
    # path: "../flutter_geofire"

  app_settings: ^3.0.1
  onesignal_flutter: 2.1.0
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.3+3
  # flutter_local_notifications: ^0.8.2

  google_api_availability: ^2.0.3

  showcaseview: ^0.1.5
  rate_my_app: ^0.6.0+2
  shared_preferences: ^0.5.6+3
  url_launcher: ^5.4.2
  barcode_scan: ^2.0.1
  share: ^0.6.3+6
  provider: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: SavourIcons
      fonts:
        - asset: fonts/SavourIcons.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/login_background.jpg
    - images/permissions.jpg
    - images/Savour_Deals_White.png
    - images/Savour_Deals_FullColor-white-back.png
    - images/Savour_White.png
    - images/glass-and-fork.png
    - images/tags.png
    - images/tags_filled.png
    - images/vendor.png
    - images/vendor_filled.png
    - images/user.png
    - images/user_filled.png
    - images/wallet_filled.png
    - images/like.png
    - images/like_filled.png
    - images/user_icon.png
    - images/menu-dots.png
    - images/diamond.png
    - images/diamond_filled.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  # - family: SavourIcons
  #   fonts:
  #     - asset: fonts/SavourIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttfs
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
