/// Flutter icons SavourIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SavourIcons
///      fonts:
///       - asset: fonts/SavourIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SavourIcons {
  SavourIcons._();

  static const _kFontFam = 'SavourIcons';

  static const IconData filled_heart = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData icons8_friends_filled_2 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData icons8_friends = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData icons8_like_2 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData icons8_price_tag_filled = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData icons8_price_tag_2 = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData icons8_small_business_filled = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData icons8_small_business = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData icons8_user_male_circle_filled = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData icons8_user_male_circle = const IconData(0xe809, fontFamily: _kFontFam);
}
